---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

# 12.1 Prerequisites 

I registered for a github account, installed r and r studio, installed git, introduced myself to git, and confirmed I can push to / pull from the command line. 

# 12.2 Make a repo on GitHub 

I created the lab1_team16 team and copied the code url for it. 

# 12.3 Clone the test GitHub repository to your computer via RStudio 

I did file, new project, version control, git, and then copied the url for the lab1_team16  repository. 

# 12.4 Make local Changes, save, commit 

I modified the md file by adding "This is a line from RStudio" 
In RStudio:
Clicked the “Git” tab in upper right pane.
Check “Staged” box for README.md.
Type a message in “Commit message”
Click “Commit”.

# 12.5 Push your local changes online to GitHub 


I sent my changes to GitHub my clicking the green push button.

# 12.6 Confirm the local change propagated to the GitHub remote 

I refreshed my browser and saw the changes and the message.

Hazer - I just cloned the repo and am making my first commit.\
I also Knit to update readme.md

My Lab 1 Experience (Siddhartha Gudipudi):
12.1 Prerequisites: I completed of all prerequisite steps, which includes registration on GitHub, installation of R, RStudio, and Git, and successful push/pull verification.

12.2 Make a repo on GitHub: I created a new repository on GitHub.

12.3 Clone the test GitHub repository to your computer via RStudio: I initiated a new RStudio Project using Version Control, pasted the GitHub repository URL, and successfully cloned the project into Rstudio.

This is line from R studio- Siddhartha Gudipudi

12.4 Make local changes, save, commit: I added a line to the README file in RStudio, saved it, and then clicked 'Commit'.
12.5 Push your local changes online to GitHub: I clicked the "Push" button in RStudio to upload my changes to GitHub..

12.6 Confirm the local change propagated to the GitHub remote: After refreshing the GitHub page, I verified that the changes I made in RStudio are in github.

